/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['img[_ngcontent-%COMP%] {\r\n    display: inline-block;\r\n    width: 128px;\r\n    height: 128px;\r\n    background-color: white;\r\n}\r\n\r\nmd-grid-tile[_ngcontent-%COMP%] {\r\n    border: solid grey 4px;\r\n    cursor: pointer;\r\n}\r\n\r\nmd-sidenav-container[_ngcontent-%COMP%] {\r\n  margin: 0;\r\n  height: 825px;\r\n}\r\n\r\nmd-sidenav[_ngcontent-%COMP%] { \r\n    height: 825px;\r\n}\r\n\r\nh3[_ngcontent-%COMP%] {\r\n    text-align: center;\r\n}\r\n\r\nbutton[_ngcontent-%COMP%]:focus {outline:0;}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL3N0dWRlbnQvZ2FtZXMvZ3JhZGUtc2lkZW5hdi9ncmFkZS1zaWRlbmF2LmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL3N0dWRlbnQvZ2FtZXMvZ3JhZGUtc2lkZW5hdi9ncmFkZS1zaWRlbmF2LmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
