/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './end-game-dialog.module';
import * as import2 from '@angular/material';
import * as import3 from '@angular/common';
import * as import4 from '@angular/forms';
import * as import5 from '@angular/http';
import * as import6 from '@angular/flex-layout/media-query/_module';
import * as import7 from '@angular/flex-layout/flexbox/_module';
import * as import8 from '@angular/flex-layout/media-query/breakpoints/break-point-registry';
import * as import9 from '@angular/flex-layout/media-query/match-media';
import * as import10 from '../../../../../node_modules/@angular/material/typings/index.ngfactory';
import * as import11 from './end-game-dialog.component.ngfactory';
import * as import12 from '@angular/platform-browser';
import * as import13 from '@angular/flex-layout/media-query/breakpoints/break-points-provider';
import * as import14 from '@angular/flex-layout/media-query/media-monitor-provider';
import * as import15 from '@angular/flex-layout/media-query/media-monitor';
import * as import16 from '@angular/flex-layout/media-query/observable-media-provider';
import * as import17 from '@angular/flex-layout/media-query/observable-media';
import * as import18 from '@angular/flex-layout/media-query/breakpoints/break-points-token';
class EndGameDialogModuleInjector extends import0.ɵNgModuleInjector<import1.EndGameDialogModule> {
  _CompatibilityModule_0:import2.CompatibilityModule;
  _MdRippleModule_1:import2.MdRippleModule;
  _CommonModule_2:import3.CommonModule;
  _MdSelectionModule_3:import2.MdSelectionModule;
  _MdOptionModule_4:import2.MdOptionModule;
  _PortalModule_5:import2.PortalModule;
  _OverlayModule_6:import2.OverlayModule;
  _MdAutocompleteModule_7:import2.MdAutocompleteModule;
  _StyleModule_8:import2.StyleModule;
  _MdButtonModule_9:import2.MdButtonModule;
  _ɵba_10:import4.ɵba;
  _FormsModule_11:import4.FormsModule;
  _MdButtonToggleModule_12:import2.MdButtonToggleModule;
  _MdCardModule_13:import2.MdCardModule;
  _MdChipsModule_14:import2.MdChipsModule;
  _MdCheckboxModule_15:import2.MdCheckboxModule;
  _PlatformModule_16:import2.PlatformModule;
  _A11yModule_17:import2.A11yModule;
  _MdDialogModule_18:import2.MdDialogModule;
  _MdLineModule_19:import2.MdLineModule;
  _MdGridListModule_20:import2.MdGridListModule;
  _HttpModule_21:import5.HttpModule;
  _MdIconModule_22:import2.MdIconModule;
  _MdInputModule_23:import2.MdInputModule;
  _MdListModule_24:import2.MdListModule;
  _MdMenuModule_25:import2.MdMenuModule;
  _MdProgressBarModule_26:import2.MdProgressBarModule;
  _MdProgressSpinnerModule_27:import2.MdProgressSpinnerModule;
  _MdRadioModule_28:import2.MdRadioModule;
  _MdSelectModule_29:import2.MdSelectModule;
  _MdSidenavModule_30:import2.MdSidenavModule;
  _RtlModule_31:import2.RtlModule;
  _MdSliderModule_32:import2.MdSliderModule;
  _MdSlideToggleModule_33:import2.MdSlideToggleModule;
  _MdSnackBarModule_34:import2.MdSnackBarModule;
  _ObserveContentModule_35:import2.ObserveContentModule;
  _MdTabsModule_36:import2.MdTabsModule;
  _MdToolbarModule_37:import2.MdToolbarModule;
  _MdTooltipModule_38:import2.MdTooltipModule;
  _MaterialModule_39:import2.MaterialModule;
  _MediaQueriesModule_40:import6.MediaQueriesModule;
  _FlexLayoutModule_41:import7.FlexLayoutModule;
  _EndGameDialogModule_42:import1.EndGameDialogModule;
  __ScrollDispatcher_43:any;
  __ɵh_44:any;
  __NgLocalization_45:import3.NgLocaleLocalization;
  __OverlayContainer_46:any;
  __ɵk_47:import2.ɵk;
  __Overlay_48:import2.Overlay;
  __FocusOriginMonitor_49:any;
  __ɵi_50:import4.ɵi;
  __UniqueSelectionDispatcher_51:any;
  __Platform_52:import2.Platform;
  __InteractivityChecker_53:import2.InteractivityChecker;
  __FocusTrapFactory_54:import2.FocusTrapFactory;
  __LiveAnnouncer_55:any;
  __MdDialog_56:import2.MdDialog;
  __BrowserXhr_57:import5.BrowserXhr;
  __ResponseOptions_58:import5.BaseResponseOptions;
  __XSRFStrategy_59:any;
  __XHRBackend_60:import5.XHRBackend;
  __RequestOptions_61:import5.BaseRequestOptions;
  __Http_62:any;
  __MdIconRegistry_63:any;
  __HAMMER_GESTURE_CONFIG_64:import2.GestureConfig;
  __MdSnackBar_65:import2.MdSnackBar;
  __BREAKPOINTS_66:any;
  __BreakPointRegistry_67:import8.BreakPointRegistry;
  __MatchMedia_68:import9.MatchMedia;
  __MediaMonitor_69:any;
  __ObservableMedia_70:any;
  constructor(parent:import0.Injector) {
    super(parent,[
      import10.MdDialogContainerNgFactory,
      import10.MdSnackBarContainerNgFactory,
      import10.SimpleSnackBarNgFactory,
      import10.TooltipComponentNgFactory,
      import11.EndGameDialogComponentNgFactory,
      import11.WinDialogInnerTextComponentNgFactory,
      import11.LoseDialogInnerTextComponentNgFactory
    ]
    ,[
      import11.EndGameDialogComponentNgFactory,
      import11.WinDialogInnerTextComponentNgFactory,
      import11.LoseDialogInnerTextComponentNgFactory
    ]
    );
  }
  get _ScrollDispatcher_43():any {
    if ((this.__ScrollDispatcher_43 == null)) { (this.__ScrollDispatcher_43 = import2.ɵc(this.parent.get(import2.ScrollDispatcher,(null as any)),this.parent.get(import0.NgZone))); }
    return this.__ScrollDispatcher_43;
  }
  get _ɵh_44():any {
    if ((this.__ɵh_44 == null)) { (this.__ɵh_44 = import2.ɵi(this.parent.get(import2.ɵh,(null as any)),this._ScrollDispatcher_43)); }
    return this.__ɵh_44;
  }
  get _NgLocalization_45():import3.NgLocaleLocalization {
    if ((this.__NgLocalization_45 == null)) { (this.__NgLocalization_45 = new import3.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_45;
  }
  get _OverlayContainer_46():any {
    if ((this.__OverlayContainer_46 == null)) { (this.__OverlayContainer_46 = import2.ɵa(this.parent.get(import2.OverlayContainer,(null as any)))); }
    return this.__OverlayContainer_46;
  }
  get _ɵk_47():import2.ɵk {
    if ((this.__ɵk_47 == null)) { (this.__ɵk_47 = new import2.ɵk(this._ɵh_44)); }
    return this.__ɵk_47;
  }
  get _Overlay_48():import2.Overlay {
    if ((this.__Overlay_48 == null)) { (this.__Overlay_48 = new import2.Overlay(this._OverlayContainer_46,this.componentFactoryResolver,this._ɵk_47,this.parent.get(import0.ApplicationRef),this,this.parent.get(import0.NgZone))); }
    return this.__Overlay_48;
  }
  get _FocusOriginMonitor_49():any {
    if ((this.__FocusOriginMonitor_49 == null)) { (this.__FocusOriginMonitor_49 = import2.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY(this.parent.get(import2.FocusOriginMonitor,(null as any)),this.parent.get(import0.NgZone))); }
    return this.__FocusOriginMonitor_49;
  }
  get _ɵi_50():import4.ɵi {
    if ((this.__ɵi_50 == null)) { (this.__ɵi_50 = new import4.ɵi()); }
    return this.__ɵi_50;
  }
  get _UniqueSelectionDispatcher_51():any {
    if ((this.__UniqueSelectionDispatcher_51 == null)) { (this.__UniqueSelectionDispatcher_51 = import2.ɵg(this.parent.get(import2.UniqueSelectionDispatcher,(null as any)))); }
    return this.__UniqueSelectionDispatcher_51;
  }
  get _Platform_52():import2.Platform {
    if ((this.__Platform_52 == null)) { (this.__Platform_52 = new import2.Platform()); }
    return this.__Platform_52;
  }
  get _InteractivityChecker_53():import2.InteractivityChecker {
    if ((this.__InteractivityChecker_53 == null)) { (this.__InteractivityChecker_53 = new import2.InteractivityChecker(this._Platform_52)); }
    return this.__InteractivityChecker_53;
  }
  get _FocusTrapFactory_54():import2.FocusTrapFactory {
    if ((this.__FocusTrapFactory_54 == null)) { (this.__FocusTrapFactory_54 = new import2.FocusTrapFactory(this._InteractivityChecker_53,this.parent.get(import0.NgZone))); }
    return this.__FocusTrapFactory_54;
  }
  get _LiveAnnouncer_55():any {
    if ((this.__LiveAnnouncer_55 == null)) { (this.__LiveAnnouncer_55 = import2.ɵf(this.parent.get(import2.LiveAnnouncer,(null as any)),this.parent.get(import2.LIVE_ANNOUNCER_ELEMENT_TOKEN,(null as any)))); }
    return this.__LiveAnnouncer_55;
  }
  get _MdDialog_56():import2.MdDialog {
    if ((this.__MdDialog_56 == null)) { (this.__MdDialog_56 = new import2.MdDialog(this._Overlay_48,this,this.parent.get(import2.MdDialog,(null as any)))); }
    return this.__MdDialog_56;
  }
  get _BrowserXhr_57():import5.BrowserXhr {
    if ((this.__BrowserXhr_57 == null)) { (this.__BrowserXhr_57 = new import5.BrowserXhr()); }
    return this.__BrowserXhr_57;
  }
  get _ResponseOptions_58():import5.BaseResponseOptions {
    if ((this.__ResponseOptions_58 == null)) { (this.__ResponseOptions_58 = new import5.BaseResponseOptions()); }
    return this.__ResponseOptions_58;
  }
  get _XSRFStrategy_59():any {
    if ((this.__XSRFStrategy_59 == null)) { (this.__XSRFStrategy_59 = import5.ɵb()); }
    return this.__XSRFStrategy_59;
  }
  get _XHRBackend_60():import5.XHRBackend {
    if ((this.__XHRBackend_60 == null)) { (this.__XHRBackend_60 = new import5.XHRBackend(this._BrowserXhr_57,this._ResponseOptions_58,this._XSRFStrategy_59)); }
    return this.__XHRBackend_60;
  }
  get _RequestOptions_61():import5.BaseRequestOptions {
    if ((this.__RequestOptions_61 == null)) { (this.__RequestOptions_61 = new import5.BaseRequestOptions()); }
    return this.__RequestOptions_61;
  }
  get _Http_62():any {
    if ((this.__Http_62 == null)) { (this.__Http_62 = import5.ɵc(this._XHRBackend_60,this._RequestOptions_61)); }
    return this.__Http_62;
  }
  get _MdIconRegistry_63():any {
    if ((this.__MdIconRegistry_63 == null)) { (this.__MdIconRegistry_63 = import2.ICON_REGISTRY_PROVIDER_FACTORY(this.parent.get(import2.MdIconRegistry,(null as any)),this._Http_62,this.parent.get(import12.DomSanitizer))); }
    return this.__MdIconRegistry_63;
  }
  get _HAMMER_GESTURE_CONFIG_64():import2.GestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_64 == null)) { (this.__HAMMER_GESTURE_CONFIG_64 = new import2.GestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_64;
  }
  get _MdSnackBar_65():import2.MdSnackBar {
    if ((this.__MdSnackBar_65 == null)) { (this.__MdSnackBar_65 = new import2.MdSnackBar(this._Overlay_48,this._LiveAnnouncer_55,this.parent.get(import2.MdSnackBar,(null as any)))); }
    return this.__MdSnackBar_65;
  }
  get _BREAKPOINTS_66():any {
    if ((this.__BREAKPOINTS_66 == null)) { (this.__BREAKPOINTS_66 = import13.DEFAULT_BREAKPOINTS_PROVIDER_FACTORY()); }
    return this.__BREAKPOINTS_66;
  }
  get _BreakPointRegistry_67():import8.BreakPointRegistry {
    if ((this.__BreakPointRegistry_67 == null)) { (this.__BreakPointRegistry_67 = new import8.BreakPointRegistry(this._BREAKPOINTS_66)); }
    return this.__BreakPointRegistry_67;
  }
  get _MatchMedia_68():import9.MatchMedia {
    if ((this.__MatchMedia_68 == null)) { (this.__MatchMedia_68 = new import9.MatchMedia(this.parent.get(import0.NgZone))); }
    return this.__MatchMedia_68;
  }
  get _MediaMonitor_69():any {
    if ((this.__MediaMonitor_69 == null)) { (this.__MediaMonitor_69 = import14.MEDIA_MONITOR_PROVIDER_FACTORY(this.parent.get(import15.MediaMonitor,(null as any)),this._BreakPointRegistry_67,this._MatchMedia_68)); }
    return this.__MediaMonitor_69;
  }
  get _ObservableMedia_70():any {
    if ((this.__ObservableMedia_70 == null)) { (this.__ObservableMedia_70 = import16.OBSERVABLE_MEDIA_PROVIDER_FACTORY(this.parent.get(import17.ObservableMedia,(null as any)),this._MatchMedia_68,this._BreakPointRegistry_67)); }
    return this.__ObservableMedia_70;
  }
  createInternal():import1.EndGameDialogModule {
    this._CompatibilityModule_0 = new import2.CompatibilityModule(this.parent.get(import12.DOCUMENT,(null as any)));
    this._MdRippleModule_1 = new import2.MdRippleModule();
    this._CommonModule_2 = new import3.CommonModule();
    this._MdSelectionModule_3 = new import2.MdSelectionModule();
    this._MdOptionModule_4 = new import2.MdOptionModule();
    this._PortalModule_5 = new import2.PortalModule();
    this._OverlayModule_6 = new import2.OverlayModule();
    this._MdAutocompleteModule_7 = new import2.MdAutocompleteModule();
    this._StyleModule_8 = new import2.StyleModule();
    this._MdButtonModule_9 = new import2.MdButtonModule();
    this._ɵba_10 = new import4.ɵba();
    this._FormsModule_11 = new import4.FormsModule();
    this._MdButtonToggleModule_12 = new import2.MdButtonToggleModule();
    this._MdCardModule_13 = new import2.MdCardModule();
    this._MdChipsModule_14 = new import2.MdChipsModule();
    this._MdCheckboxModule_15 = new import2.MdCheckboxModule();
    this._PlatformModule_16 = new import2.PlatformModule();
    this._A11yModule_17 = new import2.A11yModule();
    this._MdDialogModule_18 = new import2.MdDialogModule();
    this._MdLineModule_19 = new import2.MdLineModule();
    this._MdGridListModule_20 = new import2.MdGridListModule();
    this._HttpModule_21 = new import5.HttpModule();
    this._MdIconModule_22 = new import2.MdIconModule();
    this._MdInputModule_23 = new import2.MdInputModule();
    this._MdListModule_24 = new import2.MdListModule();
    this._MdMenuModule_25 = new import2.MdMenuModule();
    this._MdProgressBarModule_26 = new import2.MdProgressBarModule();
    this._MdProgressSpinnerModule_27 = new import2.MdProgressSpinnerModule();
    this._MdRadioModule_28 = new import2.MdRadioModule();
    this._MdSelectModule_29 = new import2.MdSelectModule();
    this._MdSidenavModule_30 = new import2.MdSidenavModule();
    this._RtlModule_31 = new import2.RtlModule();
    this._MdSliderModule_32 = new import2.MdSliderModule();
    this._MdSlideToggleModule_33 = new import2.MdSlideToggleModule();
    this._MdSnackBarModule_34 = new import2.MdSnackBarModule();
    this._ObserveContentModule_35 = new import2.ObserveContentModule();
    this._MdTabsModule_36 = new import2.MdTabsModule();
    this._MdToolbarModule_37 = new import2.MdToolbarModule();
    this._MdTooltipModule_38 = new import2.MdTooltipModule();
    this._MaterialModule_39 = new import2.MaterialModule();
    this._MediaQueriesModule_40 = new import6.MediaQueriesModule();
    this._FlexLayoutModule_41 = new import7.FlexLayoutModule();
    this._EndGameDialogModule_42 = new import1.EndGameDialogModule();
    return this._EndGameDialogModule_42;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CompatibilityModule)) { return this._CompatibilityModule_0; }
    if ((token === import2.MdRippleModule)) { return this._MdRippleModule_1; }
    if ((token === import3.CommonModule)) { return this._CommonModule_2; }
    if ((token === import2.MdSelectionModule)) { return this._MdSelectionModule_3; }
    if ((token === import2.MdOptionModule)) { return this._MdOptionModule_4; }
    if ((token === import2.PortalModule)) { return this._PortalModule_5; }
    if ((token === import2.OverlayModule)) { return this._OverlayModule_6; }
    if ((token === import2.MdAutocompleteModule)) { return this._MdAutocompleteModule_7; }
    if ((token === import2.StyleModule)) { return this._StyleModule_8; }
    if ((token === import2.MdButtonModule)) { return this._MdButtonModule_9; }
    if ((token === import4.ɵba)) { return this._ɵba_10; }
    if ((token === import4.FormsModule)) { return this._FormsModule_11; }
    if ((token === import2.MdButtonToggleModule)) { return this._MdButtonToggleModule_12; }
    if ((token === import2.MdCardModule)) { return this._MdCardModule_13; }
    if ((token === import2.MdChipsModule)) { return this._MdChipsModule_14; }
    if ((token === import2.MdCheckboxModule)) { return this._MdCheckboxModule_15; }
    if ((token === import2.PlatformModule)) { return this._PlatformModule_16; }
    if ((token === import2.A11yModule)) { return this._A11yModule_17; }
    if ((token === import2.MdDialogModule)) { return this._MdDialogModule_18; }
    if ((token === import2.MdLineModule)) { return this._MdLineModule_19; }
    if ((token === import2.MdGridListModule)) { return this._MdGridListModule_20; }
    if ((token === import5.HttpModule)) { return this._HttpModule_21; }
    if ((token === import2.MdIconModule)) { return this._MdIconModule_22; }
    if ((token === import2.MdInputModule)) { return this._MdInputModule_23; }
    if ((token === import2.MdListModule)) { return this._MdListModule_24; }
    if ((token === import2.MdMenuModule)) { return this._MdMenuModule_25; }
    if ((token === import2.MdProgressBarModule)) { return this._MdProgressBarModule_26; }
    if ((token === import2.MdProgressSpinnerModule)) { return this._MdProgressSpinnerModule_27; }
    if ((token === import2.MdRadioModule)) { return this._MdRadioModule_28; }
    if ((token === import2.MdSelectModule)) { return this._MdSelectModule_29; }
    if ((token === import2.MdSidenavModule)) { return this._MdSidenavModule_30; }
    if ((token === import2.RtlModule)) { return this._RtlModule_31; }
    if ((token === import2.MdSliderModule)) { return this._MdSliderModule_32; }
    if ((token === import2.MdSlideToggleModule)) { return this._MdSlideToggleModule_33; }
    if ((token === import2.MdSnackBarModule)) { return this._MdSnackBarModule_34; }
    if ((token === import2.ObserveContentModule)) { return this._ObserveContentModule_35; }
    if ((token === import2.MdTabsModule)) { return this._MdTabsModule_36; }
    if ((token === import2.MdToolbarModule)) { return this._MdToolbarModule_37; }
    if ((token === import2.MdTooltipModule)) { return this._MdTooltipModule_38; }
    if ((token === import2.MaterialModule)) { return this._MaterialModule_39; }
    if ((token === import6.MediaQueriesModule)) { return this._MediaQueriesModule_40; }
    if ((token === import7.FlexLayoutModule)) { return this._FlexLayoutModule_41; }
    if ((token === import1.EndGameDialogModule)) { return this._EndGameDialogModule_42; }
    if ((token === import2.ScrollDispatcher)) { return this._ScrollDispatcher_43; }
    if ((token === import2.ɵh)) { return this._ɵh_44; }
    if ((token === import3.NgLocalization)) { return this._NgLocalization_45; }
    if ((token === import2.OverlayContainer)) { return this._OverlayContainer_46; }
    if ((token === import2.ɵk)) { return this._ɵk_47; }
    if ((token === import2.Overlay)) { return this._Overlay_48; }
    if ((token === import2.FocusOriginMonitor)) { return this._FocusOriginMonitor_49; }
    if ((token === import4.ɵi)) { return this._ɵi_50; }
    if ((token === import2.UniqueSelectionDispatcher)) { return this._UniqueSelectionDispatcher_51; }
    if ((token === import2.Platform)) { return this._Platform_52; }
    if ((token === import2.InteractivityChecker)) { return this._InteractivityChecker_53; }
    if ((token === import2.FocusTrapFactory)) { return this._FocusTrapFactory_54; }
    if ((token === import2.LiveAnnouncer)) { return this._LiveAnnouncer_55; }
    if ((token === import2.MdDialog)) { return this._MdDialog_56; }
    if ((token === import5.BrowserXhr)) { return this._BrowserXhr_57; }
    if ((token === import5.ResponseOptions)) { return this._ResponseOptions_58; }
    if ((token === import5.XSRFStrategy)) { return this._XSRFStrategy_59; }
    if ((token === import5.XHRBackend)) { return this._XHRBackend_60; }
    if ((token === import5.RequestOptions)) { return this._RequestOptions_61; }
    if ((token === import5.Http)) { return this._Http_62; }
    if ((token === import2.MdIconRegistry)) { return this._MdIconRegistry_63; }
    if ((token === import12.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_64; }
    if ((token === import2.MdSnackBar)) { return this._MdSnackBar_65; }
    if ((token === import18.BREAKPOINTS)) { return this._BREAKPOINTS_66; }
    if ((token === import8.BreakPointRegistry)) { return this._BreakPointRegistry_67; }
    if ((token === import9.MatchMedia)) { return this._MatchMedia_68; }
    if ((token === import15.MediaMonitor)) { return this._MediaMonitor_69; }
    if ((token === import17.ObservableMedia)) { return this._ObservableMedia_70; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const EndGameDialogModuleNgFactory:import0.NgModuleFactory<import1.EndGameDialogModule> = new import0.NgModuleFactory<any>(EndGameDialogModuleInjector,import1.EndGameDialogModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL3N0dWRlbnQvZ2FtZXMvZW5kLWdhbWUtZGlhbG9nL2VuZC1nYW1lLWRpYWxvZy5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL3N0dWRlbnQvZ2FtZXMvZW5kLWdhbWUtZGlhbG9nL2VuZC1nYW1lLWRpYWxvZy5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
