/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.frame[_ngcontent-%COMP%] {\r\n    width: 800px;\r\n    min-width: 800px;\r\n    height: 600px;\r\n    min-height: 600px;\r\n    border: solid black;\r\n    margin: auto;\r\n}\r\n\r\n.pipe[_ngcontent-%COMP%] {\r\n    height: 125px;\r\n    width: 200px;\r\n    border: solid black;\r\n    text-align: center;\r\n    align-items: center;\r\n    cursor: pointer;\r\n}\r\n\r\n.pipe-text[_ngcontent-%COMP%] {\r\n    margin-top: 40px;\r\n\r\n}\r\n\r\n.box[_ngcontent-%COMP%] {\r\n    height: 75px;\r\n    width: 200px;\r\n    border: solid black;\r\n}\r\n\r\n.wall[_ngcontent-%COMP%] {\r\n    border: solid black;\r\n    z-index: 2;\r\n    background-color: white;\r\n}\r\n\r\n.solution[_ngcontent-%COMP%] {\r\n    position: relative;\r\n    border: solid black;\r\n    width: 95px;\r\n    height: 95px;\r\n    left: -120px;\r\n    text-align: center;\r\n    align-items: center;\r\n}\r\n\r\n.solution-text[_ngcontent-%COMP%] {\r\n    margin-top: 40px;\r\n}\r\n\r\n.title[_ngcontent-%COMP%]{\r\n    text-align: center;\r\n}\r\n\r\n.score[_ngcontent-%COMP%]{\r\n    float: right;\r\n    margin-right: 10%;\r\n\r\n}\r\n\r\n.errors[_ngcontent-%COMP%]{\r\n    margin-left: 10%;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL3N0dWRlbnQvZ2FtZXMvbWF0aC1jbG91ZHMvbWF0aC1jbG91ZHMuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9NYWhhZWxhL0Rlc2t0b3Avc2Nob2xhcnF1ZXN0LXJlZmFjdG9yL2Fzc2V0cy9hcHAvc3R1ZGVudC9nYW1lcy9tYXRoLWNsb3Vkcy9tYXRoLWNsb3Vkcy5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
