/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['div[_ngcontent-%COMP%] {\r\nmargin:auto;\r\nwidth: 250px;\r\nmargin-top: 250px;\r\ntext-align: center;\r\n}\r\n\r\n#backdrop[_ngcontent-%COMP%]{\r\n    margin-top: 100px;\r\n    background-color: cornsilk;\r\n    padding-top: 50px;\r\n    padding-bottom: 50px;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL2F1dGgvZW1haWwtdmVyaWZpZWQvZW1haWwtdmVyaWZpZWQuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9NYWhhZWxhL0Rlc2t0b3Avc2Nob2xhcnF1ZXN0LXJlZmFjdG9yL2Fzc2V0cy9hcHAvYXV0aC9lbWFpbC12ZXJpZmllZC9lbWFpbC12ZXJpZmllZC5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
