/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './cursor-follower.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../eyes/eyes.component.ngfactory';
import * as import3 from '../eyes/eyes.component';
import * as import4 from '@angular/common';
import * as import5 from './cursor-follower.component';
import * as import6 from '../cursor-follower.service';
const styles_CursorFollowerListComponent:any[] = [import0.styles];
export const RenderType_CursorFollowerListComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_CursorFollowerListComponent,
      data: {'animation': [{
        name: 'show',
        definitions: [
          {
            type: 0,
            name: 'invisible',
            styles: {
              type: 6,
              styles: {opacity: 0}
            }

          }
          ,
          {
            type: 0,
            name: 'visible',
            styles: {
              type: 6,
              styles: {opacity: 1}
            }

          }
          ,
          {
            type: 1,
            expr: 'invisible => visible',
            animation: {
              type: 4,
              styles: (null as any),
              timings: 2000
            }

          }
          ,
          {
            type: 1,
            expr: 'visible => invisible',
            animation: {
              type: 4,
              styles: (null as any),
              timings: 1000
            }

          }

        ]

      }
  ]}
}
);
function View_CursorFollowerListComponent_1(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),4,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n        '])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'sq-eyes',([] as any[]),(null as any),(null as any),(null as any),import2.View_EyesComponent_0,import2.RenderType_EyesComponent)),
    import1.ɵdid(2121728,(null as any),0,import3.EyesComponent,[import1.Renderer],{
      xPos: [
        0,
        'xPos'
      ]
      ,
      yPos: [
        1,
        'yPos'
      ]

    }
    ,(null as any)),
    (l()(),import1.ɵted((null as any),['\n    ']))
  ]
  ,(ck,v) => {
    var co:any = v.component;
    const currVal_0:any = co.xPos;
    const currVal_1:any = co.yPos;
    ck(v,3,0,currVal_0,currVal_1);
  },(null as any));
}
export function View_CursorFollowerListComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    import1.ɵqud(201326592,1,{cursorFollower: 0}),
    (l()(),import1.ɵeld(8388608,[
      [
        1,
        3
      ]
      ,
      [
        'cursorFollower',
        1
      ]

    ]
    ,(null as any),0,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n'])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),5,'div',([] as any[]),[[
        24,
        '@show',
        0
      ]
    ],(null as any),(null as any),(null as any),(null as any))),
      import1.ɵdid(8192,(null as any),0,import4.NgSwitch,([] as any[]),{ngSwitch: [
        0,
        'ngSwitch'
      ]
    },(null as any)),
    (l()(),import1.ɵted((null as any),['\n    '])),
    (l()(),import1.ɵand(8388608,(null as any),(null as any),1,(null as any),View_CursorFollowerListComponent_1)),
    import1.ɵdid(139264,(null as any),0,import4.NgSwitchCase,[
      import1.ViewContainerRef,
      import1.TemplateRef,
      import4.NgSwitch
    ]
      ,{ngSwitchCase: [
        0,
        'ngSwitchCase'
      ]
    },(null as any)),
    (l()(),import1.ɵted((null as any),['\n'])),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    var co:import5.CursorFollowerListComponent = v.component;
    const currVal_1:any = co.cursorFollowerService.selectedCursorFollower.value;
    ck(v,4,0,currVal_1);
    const currVal_2:any = 2;
    ck(v,7,0,currVal_2);
  },(ck,v) => {
    var co:import5.CursorFollowerListComponent = v.component;
    const currVal_0:any = co.show;
    ck(v,3,0,currVal_0);
  });
}
function View_CursorFollowerListComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(8388608,(null as any),(null as any),1,'sq-cursor-follower',([] as any[]),(null as any),(null as any),(null as any),View_CursorFollowerListComponent_0,RenderType_CursorFollowerListComponent)),
    import1.ɵdid(2121728,(null as any),0,import5.CursorFollowerListComponent,[
      import1.ViewContainerRef,
      import1.ComponentFactoryResolver,
      import6.CursorFollowerService,
      import1.ElementRef
    ]
    ,(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const CursorFollowerListComponentNgFactory:import1.ComponentFactory<import5.CursorFollowerListComponent> = import1.ɵccf('sq-cursor-follower',import5.CursorFollowerListComponent,View_CursorFollowerListComponent_Host_0,{
  xPos: 'xPos',
  yPos: 'yPos'
}
,{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL2N1cnNvci1mb2xsb3dlci9jdXJzb3ItZm9sbG93ZXIvY3Vyc29yLWZvbGxvd2VyLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9NYWhhZWxhL0Rlc2t0b3Avc2Nob2xhcnF1ZXN0LXJlZmFjdG9yL2Fzc2V0cy9hcHAvY3Vyc29yLWZvbGxvd2VyL2N1cnNvci1mb2xsb3dlci9jdXJzb3ItZm9sbG93ZXIuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL2N1cnNvci1mb2xsb3dlci9jdXJzb3ItZm9sbG93ZXIvY3Vyc29yLWZvbGxvd2VyLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL2N1cnNvci1mb2xsb3dlci9jdXJzb3ItZm9sbG93ZXIvY3Vyc29yLWZvbGxvd2VyLmNvbXBvbmVudC50cy5DdXJzb3JGb2xsb3dlckxpc3RDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2ICNjdXJzb3JGb2xsb3dlciA+PC9kaXY+XHJcbjxkaXYgW25nU3dpdGNoXT1cImN1cnNvckZvbGxvd2VyU2VydmljZS5zZWxlY3RlZEN1cnNvckZvbGxvd2VyLnZhbHVlXCIgW0BzaG93XT1cInNob3dcIiA+XHJcbiAgICA8ZGl2ICpuZ1N3aXRjaENhc2U9XCIyXCI+XHJcbiAgICAgICAgPHNxLWV5ZXMgW3hQb3NdPVwieFBvc1wiIFt5UG9zXT1cInlQb3NcIj48L3NxLWV5ZXM+XHJcbiAgICA8L2Rpdj5cclxuPC9kaXY+XHJcbiIsIjxzcS1jdXJzb3ItZm9sbG93ZXI+PC9zcS1jdXJzb3ItZm9sbG93ZXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDRUk7SUFBdUI7SUFDbkI7Z0JBQUE7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7SUFBQTtLQUFBO0lBQStDOzs7O0lBQXRDO0lBQWM7SUFBdkIsU0FBUyxVQUFjLFNBQXZCOzs7Ozs7SUFIUjtNQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO0tBQUE7SUFBNEI7TUFDNUI7UUFBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO2tCQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBcUY7SUFDakY7Z0JBQUE7Ozs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFFTTtJQUNKOzs7O0lBSkQ7SUFBTCxTQUFLLFNBQUw7SUFDUztJQUFMLFNBQUssU0FBTDs7O0lBRGlFO0lBQXJFLFNBQXFFLFNBQXJFOzs7OztJQ0RBO2dCQUFBOzs7OztJQUFBO0tBQUE7Ozs7Ozs7OyJ9
