/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './cursor.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from './cursor.component';
import * as import3 from '../cursor.service';
const styles_CursorComponent:any[] = [import0.styles];
export const RenderType_CursorComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_CursorComponent,
      data: {'animation': [{
        name: 'show',
        definitions: [
          {
            type: 0,
            name: 'invisible',
            styles: {
              type: 6,
              styles: {opacity: 0}
            }

          }
          ,
          {
            type: 0,
            name: 'visible',
            styles: {
              type: 6,
              styles: {opacity: 1}
            }

          }
          ,
          {
            type: 1,
            expr: 'invisible => visible',
            animation: {
              type: 4,
              styles: (null as any),
              timings: 2000
            }

          }
          ,
          {
            type: 1,
            expr: 'visible => invisible',
            animation: {
              type: 4,
              styles: (null as any),
              timings: 300
            }

          }

        ]

      }
  ]}
}
);
export function View_CursorComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    import1.ɵqud(201326592,1,{cursor: 0}),
    (l()(),import1.ɵted((null as any),['  '])),
    (l()(),import1.ɵeld(0,[
      [
        1,
        0
      ]
      ,
      [
        'cursor',
        1
      ]

    ]
    ,(null as any),0,'img',([] as any[]),[
      [
        8,
        'src',
        4
      ]
      ,
      [
        24,
        '@show',
        0
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any)))
  ]
  ,(null as any),(ck,v) => {
    var co:import2.CursorComponent = v.component;
    const currVal_0:any = co.displayedCursor;
    const currVal_1:any = co.show;
    ck(v,2,0,currVal_0,currVal_1);
  });
}
function View_CursorComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'sq-cursor',([] as any[]),(null as any),(null as any),(null as any),View_CursorComponent_0,RenderType_CursorComponent)),
    import1.ɵdid(2383872,(null as any),0,import2.CursorComponent,[
      import1.Renderer,
      import3.CursorService
    ]
    ,(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const CursorComponentNgFactory:import1.ComponentFactory<import2.CursorComponent> = import1.ɵccf('sq-cursor',import2.CursorComponent,View_CursorComponent_Host_0,{
  xPos: 'xPos',
  yPos: 'yPos'
}
,{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL2N1cnNvci9jdXJzb3IvY3Vyc29yLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9NYWhhZWxhL0Rlc2t0b3Avc2Nob2xhcnF1ZXN0LXJlZmFjdG9yL2Fzc2V0cy9hcHAvY3Vyc29yL2N1cnNvci9jdXJzb3IuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL2N1cnNvci9jdXJzb3IvY3Vyc29yLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL2N1cnNvci9jdXJzb3IvY3Vyc29yLmNvbXBvbmVudC50cy5DdXJzb3JDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCIgIDxpbWcgW3NyY109XCJkaXNwbGF5ZWRDdXJzb3JcIiAjY3Vyc29yICBbQHNob3ddPVwic2hvd1wiLz4iLCI8c3EtY3Vyc29yPjwvc3EtY3Vyc29yPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUFFO01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O0lBQUE7S0FBQTtNQUFBO1FBQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO1FBQUE7TUFBQTs7SUFBQTtLQUFBOzs7O0lBQUs7SUFBaUM7SUFBdEMsU0FBSyxVQUFpQyxTQUF0Qzs7Ozs7SUNBRjtnQkFBQTs7O0lBQUE7S0FBQTs7Ozs7Ozs7In0=
