/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './user-profile.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/material';
import * as import4 from '@angular/forms';
import * as import5 from '@angular/http';
import * as import6 from '@angular/flex-layout/media-query/_module';
import * as import7 from '@angular/flex-layout/flexbox/_module';
import * as import8 from '../../shared/card/card.module';
import * as import9 from '@angular/router';
import * as import10 from '@angular/flex-layout/media-query/breakpoints/break-point-registry';
import * as import11 from '@angular/flex-layout/media-query/match-media';
import * as import12 from '../../shared/utils/api.service';
import * as import13 from './avatar-service/avatar.service';
import * as import14 from '../../../../node_modules/@angular/material/typings/index.ngfactory';
import * as import15 from './user-profile-page/user-profile-page.component.ngfactory';
import * as import16 from './edit-avatar-page/edit-avatar-page.component.ngfactory';
import * as import17 from '@angular/platform-browser';
import * as import18 from '@angular/flex-layout/media-query/breakpoints/break-points-provider';
import * as import19 from '@angular/flex-layout/media-query/media-monitor-provider';
import * as import20 from '@angular/flex-layout/media-query/media-monitor';
import * as import21 from '@angular/flex-layout/media-query/observable-media-provider';
import * as import22 from '@angular/flex-layout/media-query/observable-media';
import * as import23 from '../../shared/utils/cookie.service';
import * as import24 from '../../shared/utils/student.service';
import * as import25 from './user-profile-page/user-profile-page.component';
import * as import26 from './edit-avatar-page/edit-avatar-page.component';
import * as import27 from '@angular/flex-layout/media-query/breakpoints/break-points-token';
class UserProfileModuleInjector extends import0.ɵNgModuleInjector<import1.UserProfileModule> {
  _CommonModule_0:import2.CommonModule;
  _CompatibilityModule_1:import3.CompatibilityModule;
  _MdRippleModule_2:import3.MdRippleModule;
  _MdSelectionModule_3:import3.MdSelectionModule;
  _MdOptionModule_4:import3.MdOptionModule;
  _PortalModule_5:import3.PortalModule;
  _OverlayModule_6:import3.OverlayModule;
  _MdAutocompleteModule_7:import3.MdAutocompleteModule;
  _StyleModule_8:import3.StyleModule;
  _MdButtonModule_9:import3.MdButtonModule;
  _ɵba_10:import4.ɵba;
  _FormsModule_11:import4.FormsModule;
  _MdButtonToggleModule_12:import3.MdButtonToggleModule;
  _MdCardModule_13:import3.MdCardModule;
  _MdChipsModule_14:import3.MdChipsModule;
  _MdCheckboxModule_15:import3.MdCheckboxModule;
  _PlatformModule_16:import3.PlatformModule;
  _A11yModule_17:import3.A11yModule;
  _MdDialogModule_18:import3.MdDialogModule;
  _MdLineModule_19:import3.MdLineModule;
  _MdGridListModule_20:import3.MdGridListModule;
  _HttpModule_21:import5.HttpModule;
  _MdIconModule_22:import3.MdIconModule;
  _MdInputModule_23:import3.MdInputModule;
  _MdListModule_24:import3.MdListModule;
  _MdMenuModule_25:import3.MdMenuModule;
  _MdProgressBarModule_26:import3.MdProgressBarModule;
  _MdProgressSpinnerModule_27:import3.MdProgressSpinnerModule;
  _MdRadioModule_28:import3.MdRadioModule;
  _MdSelectModule_29:import3.MdSelectModule;
  _MdSidenavModule_30:import3.MdSidenavModule;
  _RtlModule_31:import3.RtlModule;
  _MdSliderModule_32:import3.MdSliderModule;
  _MdSlideToggleModule_33:import3.MdSlideToggleModule;
  _MdSnackBarModule_34:import3.MdSnackBarModule;
  _ObserveContentModule_35:import3.ObserveContentModule;
  _MdTabsModule_36:import3.MdTabsModule;
  _MdToolbarModule_37:import3.MdToolbarModule;
  _MdTooltipModule_38:import3.MdTooltipModule;
  _MaterialModule_39:import3.MaterialModule;
  _MediaQueriesModule_40:import6.MediaQueriesModule;
  _FlexLayoutModule_41:import7.FlexLayoutModule;
  _CardModule_42:import8.CardModule;
  _RouterModule_43:import9.RouterModule;
  _UserProfileModule_44:import1.UserProfileModule;
  __NgLocalization_45:import2.NgLocaleLocalization;
  __ScrollDispatcher_46:any;
  __ɵh_47:any;
  __OverlayContainer_48:any;
  __ɵk_49:import3.ɵk;
  __Overlay_50:import3.Overlay;
  __FocusOriginMonitor_51:any;
  __ɵi_52:import4.ɵi;
  __UniqueSelectionDispatcher_53:any;
  __Platform_54:import3.Platform;
  __InteractivityChecker_55:import3.InteractivityChecker;
  __FocusTrapFactory_56:import3.FocusTrapFactory;
  __LiveAnnouncer_57:any;
  __MdDialog_58:import3.MdDialog;
  __BrowserXhr_59:import5.BrowserXhr;
  __ResponseOptions_60:import5.BaseResponseOptions;
  __XSRFStrategy_61:any;
  __XHRBackend_62:import5.XHRBackend;
  __RequestOptions_63:import5.BaseRequestOptions;
  __Http_64:any;
  __MdIconRegistry_65:any;
  __HAMMER_GESTURE_CONFIG_66:import3.GestureConfig;
  __MdSnackBar_67:import3.MdSnackBar;
  __BREAKPOINTS_68:any;
  __BreakPointRegistry_69:import10.BreakPointRegistry;
  __MatchMedia_70:import11.MatchMedia;
  __MediaMonitor_71:any;
  __ObservableMedia_72:any;
  __ApiService_73:import12.ApiService;
  _ROUTES_74:any[];
  __AvatarService_75:import13.AvatarService;
  constructor(parent:import0.Injector) {
    super(parent,[
      import14.MdDialogContainerNgFactory,
      import14.MdSnackBarContainerNgFactory,
      import14.SimpleSnackBarNgFactory,
      import14.TooltipComponentNgFactory,
      import15.UserProfilePageComponentNgFactory,
      import16.EditAvatarPageComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _NgLocalization_45():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_45 == null)) { (this.__NgLocalization_45 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_45;
  }
  get _ScrollDispatcher_46():any {
    if ((this.__ScrollDispatcher_46 == null)) { (this.__ScrollDispatcher_46 = import3.ɵc(this.parent.get(import3.ScrollDispatcher,(null as any)),this.parent.get(import0.NgZone))); }
    return this.__ScrollDispatcher_46;
  }
  get _ɵh_47():any {
    if ((this.__ɵh_47 == null)) { (this.__ɵh_47 = import3.ɵi(this.parent.get(import3.ɵh,(null as any)),this._ScrollDispatcher_46)); }
    return this.__ɵh_47;
  }
  get _OverlayContainer_48():any {
    if ((this.__OverlayContainer_48 == null)) { (this.__OverlayContainer_48 = import3.ɵa(this.parent.get(import3.OverlayContainer,(null as any)))); }
    return this.__OverlayContainer_48;
  }
  get _ɵk_49():import3.ɵk {
    if ((this.__ɵk_49 == null)) { (this.__ɵk_49 = new import3.ɵk(this._ɵh_47)); }
    return this.__ɵk_49;
  }
  get _Overlay_50():import3.Overlay {
    if ((this.__Overlay_50 == null)) { (this.__Overlay_50 = new import3.Overlay(this._OverlayContainer_48,this.componentFactoryResolver,this._ɵk_49,this.parent.get(import0.ApplicationRef),this,this.parent.get(import0.NgZone))); }
    return this.__Overlay_50;
  }
  get _FocusOriginMonitor_51():any {
    if ((this.__FocusOriginMonitor_51 == null)) { (this.__FocusOriginMonitor_51 = import3.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY(this.parent.get(import3.FocusOriginMonitor,(null as any)),this.parent.get(import0.NgZone))); }
    return this.__FocusOriginMonitor_51;
  }
  get _ɵi_52():import4.ɵi {
    if ((this.__ɵi_52 == null)) { (this.__ɵi_52 = new import4.ɵi()); }
    return this.__ɵi_52;
  }
  get _UniqueSelectionDispatcher_53():any {
    if ((this.__UniqueSelectionDispatcher_53 == null)) { (this.__UniqueSelectionDispatcher_53 = import3.ɵg(this.parent.get(import3.UniqueSelectionDispatcher,(null as any)))); }
    return this.__UniqueSelectionDispatcher_53;
  }
  get _Platform_54():import3.Platform {
    if ((this.__Platform_54 == null)) { (this.__Platform_54 = new import3.Platform()); }
    return this.__Platform_54;
  }
  get _InteractivityChecker_55():import3.InteractivityChecker {
    if ((this.__InteractivityChecker_55 == null)) { (this.__InteractivityChecker_55 = new import3.InteractivityChecker(this._Platform_54)); }
    return this.__InteractivityChecker_55;
  }
  get _FocusTrapFactory_56():import3.FocusTrapFactory {
    if ((this.__FocusTrapFactory_56 == null)) { (this.__FocusTrapFactory_56 = new import3.FocusTrapFactory(this._InteractivityChecker_55,this.parent.get(import0.NgZone))); }
    return this.__FocusTrapFactory_56;
  }
  get _LiveAnnouncer_57():any {
    if ((this.__LiveAnnouncer_57 == null)) { (this.__LiveAnnouncer_57 = import3.ɵf(this.parent.get(import3.LiveAnnouncer,(null as any)),this.parent.get(import3.LIVE_ANNOUNCER_ELEMENT_TOKEN,(null as any)))); }
    return this.__LiveAnnouncer_57;
  }
  get _MdDialog_58():import3.MdDialog {
    if ((this.__MdDialog_58 == null)) { (this.__MdDialog_58 = new import3.MdDialog(this._Overlay_50,this,this.parent.get(import3.MdDialog,(null as any)))); }
    return this.__MdDialog_58;
  }
  get _BrowserXhr_59():import5.BrowserXhr {
    if ((this.__BrowserXhr_59 == null)) { (this.__BrowserXhr_59 = new import5.BrowserXhr()); }
    return this.__BrowserXhr_59;
  }
  get _ResponseOptions_60():import5.BaseResponseOptions {
    if ((this.__ResponseOptions_60 == null)) { (this.__ResponseOptions_60 = new import5.BaseResponseOptions()); }
    return this.__ResponseOptions_60;
  }
  get _XSRFStrategy_61():any {
    if ((this.__XSRFStrategy_61 == null)) { (this.__XSRFStrategy_61 = import5.ɵb()); }
    return this.__XSRFStrategy_61;
  }
  get _XHRBackend_62():import5.XHRBackend {
    if ((this.__XHRBackend_62 == null)) { (this.__XHRBackend_62 = new import5.XHRBackend(this._BrowserXhr_59,this._ResponseOptions_60,this._XSRFStrategy_61)); }
    return this.__XHRBackend_62;
  }
  get _RequestOptions_63():import5.BaseRequestOptions {
    if ((this.__RequestOptions_63 == null)) { (this.__RequestOptions_63 = new import5.BaseRequestOptions()); }
    return this.__RequestOptions_63;
  }
  get _Http_64():any {
    if ((this.__Http_64 == null)) { (this.__Http_64 = import5.ɵc(this._XHRBackend_62,this._RequestOptions_63)); }
    return this.__Http_64;
  }
  get _MdIconRegistry_65():any {
    if ((this.__MdIconRegistry_65 == null)) { (this.__MdIconRegistry_65 = import3.ICON_REGISTRY_PROVIDER_FACTORY(this.parent.get(import3.MdIconRegistry,(null as any)),this._Http_64,this.parent.get(import17.DomSanitizer))); }
    return this.__MdIconRegistry_65;
  }
  get _HAMMER_GESTURE_CONFIG_66():import3.GestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_66 == null)) { (this.__HAMMER_GESTURE_CONFIG_66 = new import3.GestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_66;
  }
  get _MdSnackBar_67():import3.MdSnackBar {
    if ((this.__MdSnackBar_67 == null)) { (this.__MdSnackBar_67 = new import3.MdSnackBar(this._Overlay_50,this._LiveAnnouncer_57,this.parent.get(import3.MdSnackBar,(null as any)))); }
    return this.__MdSnackBar_67;
  }
  get _BREAKPOINTS_68():any {
    if ((this.__BREAKPOINTS_68 == null)) { (this.__BREAKPOINTS_68 = import18.DEFAULT_BREAKPOINTS_PROVIDER_FACTORY()); }
    return this.__BREAKPOINTS_68;
  }
  get _BreakPointRegistry_69():import10.BreakPointRegistry {
    if ((this.__BreakPointRegistry_69 == null)) { (this.__BreakPointRegistry_69 = new import10.BreakPointRegistry(this._BREAKPOINTS_68)); }
    return this.__BreakPointRegistry_69;
  }
  get _MatchMedia_70():import11.MatchMedia {
    if ((this.__MatchMedia_70 == null)) { (this.__MatchMedia_70 = new import11.MatchMedia(this.parent.get(import0.NgZone))); }
    return this.__MatchMedia_70;
  }
  get _MediaMonitor_71():any {
    if ((this.__MediaMonitor_71 == null)) { (this.__MediaMonitor_71 = import19.MEDIA_MONITOR_PROVIDER_FACTORY(this.parent.get(import20.MediaMonitor,(null as any)),this._BreakPointRegistry_69,this._MatchMedia_70)); }
    return this.__MediaMonitor_71;
  }
  get _ObservableMedia_72():any {
    if ((this.__ObservableMedia_72 == null)) { (this.__ObservableMedia_72 = import21.OBSERVABLE_MEDIA_PROVIDER_FACTORY(this.parent.get(import22.ObservableMedia,(null as any)),this._MatchMedia_70,this._BreakPointRegistry_69)); }
    return this.__ObservableMedia_72;
  }
  get _ApiService_73():import12.ApiService {
    if ((this.__ApiService_73 == null)) { (this.__ApiService_73 = new import12.ApiService(this._Http_64,this.parent.get(import23.CookieService),this.parent.get(import24.StudentService))); }
    return this.__ApiService_73;
  }
  get _AvatarService_75():import13.AvatarService {
    if ((this.__AvatarService_75 == null)) { (this.__AvatarService_75 = new import13.AvatarService()); }
    return this.__AvatarService_75;
  }
  createInternal():import1.UserProfileModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._CompatibilityModule_1 = new import3.CompatibilityModule(this.parent.get(import17.DOCUMENT,(null as any)));
    this._MdRippleModule_2 = new import3.MdRippleModule();
    this._MdSelectionModule_3 = new import3.MdSelectionModule();
    this._MdOptionModule_4 = new import3.MdOptionModule();
    this._PortalModule_5 = new import3.PortalModule();
    this._OverlayModule_6 = new import3.OverlayModule();
    this._MdAutocompleteModule_7 = new import3.MdAutocompleteModule();
    this._StyleModule_8 = new import3.StyleModule();
    this._MdButtonModule_9 = new import3.MdButtonModule();
    this._ɵba_10 = new import4.ɵba();
    this._FormsModule_11 = new import4.FormsModule();
    this._MdButtonToggleModule_12 = new import3.MdButtonToggleModule();
    this._MdCardModule_13 = new import3.MdCardModule();
    this._MdChipsModule_14 = new import3.MdChipsModule();
    this._MdCheckboxModule_15 = new import3.MdCheckboxModule();
    this._PlatformModule_16 = new import3.PlatformModule();
    this._A11yModule_17 = new import3.A11yModule();
    this._MdDialogModule_18 = new import3.MdDialogModule();
    this._MdLineModule_19 = new import3.MdLineModule();
    this._MdGridListModule_20 = new import3.MdGridListModule();
    this._HttpModule_21 = new import5.HttpModule();
    this._MdIconModule_22 = new import3.MdIconModule();
    this._MdInputModule_23 = new import3.MdInputModule();
    this._MdListModule_24 = new import3.MdListModule();
    this._MdMenuModule_25 = new import3.MdMenuModule();
    this._MdProgressBarModule_26 = new import3.MdProgressBarModule();
    this._MdProgressSpinnerModule_27 = new import3.MdProgressSpinnerModule();
    this._MdRadioModule_28 = new import3.MdRadioModule();
    this._MdSelectModule_29 = new import3.MdSelectModule();
    this._MdSidenavModule_30 = new import3.MdSidenavModule();
    this._RtlModule_31 = new import3.RtlModule();
    this._MdSliderModule_32 = new import3.MdSliderModule();
    this._MdSlideToggleModule_33 = new import3.MdSlideToggleModule();
    this._MdSnackBarModule_34 = new import3.MdSnackBarModule();
    this._ObserveContentModule_35 = new import3.ObserveContentModule();
    this._MdTabsModule_36 = new import3.MdTabsModule();
    this._MdToolbarModule_37 = new import3.MdToolbarModule();
    this._MdTooltipModule_38 = new import3.MdTooltipModule();
    this._MaterialModule_39 = new import3.MaterialModule();
    this._MediaQueriesModule_40 = new import6.MediaQueriesModule();
    this._FlexLayoutModule_41 = new import7.FlexLayoutModule();
    this._CardModule_42 = new import8.CardModule();
    this._RouterModule_43 = new import9.RouterModule(this.parent.get(import9.ɵa,(null as any)),this.parent.get(import9.Router,(null as any)));
    this._UserProfileModule_44 = new import1.UserProfileModule();
      this._ROUTES_74 = [[
        {
          path: '',
          component: import25.UserProfilePageComponent
        }
        ,
        {
          path: 'profile',
          component: import25.UserProfilePageComponent
        }
        ,
        {
          path: 'edit-avatar',
          component: import26.EditAvatarPageComponent
        }

      ]
    ];
    return this._UserProfileModule_44;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.CompatibilityModule)) { return this._CompatibilityModule_1; }
    if ((token === import3.MdRippleModule)) { return this._MdRippleModule_2; }
    if ((token === import3.MdSelectionModule)) { return this._MdSelectionModule_3; }
    if ((token === import3.MdOptionModule)) { return this._MdOptionModule_4; }
    if ((token === import3.PortalModule)) { return this._PortalModule_5; }
    if ((token === import3.OverlayModule)) { return this._OverlayModule_6; }
    if ((token === import3.MdAutocompleteModule)) { return this._MdAutocompleteModule_7; }
    if ((token === import3.StyleModule)) { return this._StyleModule_8; }
    if ((token === import3.MdButtonModule)) { return this._MdButtonModule_9; }
    if ((token === import4.ɵba)) { return this._ɵba_10; }
    if ((token === import4.FormsModule)) { return this._FormsModule_11; }
    if ((token === import3.MdButtonToggleModule)) { return this._MdButtonToggleModule_12; }
    if ((token === import3.MdCardModule)) { return this._MdCardModule_13; }
    if ((token === import3.MdChipsModule)) { return this._MdChipsModule_14; }
    if ((token === import3.MdCheckboxModule)) { return this._MdCheckboxModule_15; }
    if ((token === import3.PlatformModule)) { return this._PlatformModule_16; }
    if ((token === import3.A11yModule)) { return this._A11yModule_17; }
    if ((token === import3.MdDialogModule)) { return this._MdDialogModule_18; }
    if ((token === import3.MdLineModule)) { return this._MdLineModule_19; }
    if ((token === import3.MdGridListModule)) { return this._MdGridListModule_20; }
    if ((token === import5.HttpModule)) { return this._HttpModule_21; }
    if ((token === import3.MdIconModule)) { return this._MdIconModule_22; }
    if ((token === import3.MdInputModule)) { return this._MdInputModule_23; }
    if ((token === import3.MdListModule)) { return this._MdListModule_24; }
    if ((token === import3.MdMenuModule)) { return this._MdMenuModule_25; }
    if ((token === import3.MdProgressBarModule)) { return this._MdProgressBarModule_26; }
    if ((token === import3.MdProgressSpinnerModule)) { return this._MdProgressSpinnerModule_27; }
    if ((token === import3.MdRadioModule)) { return this._MdRadioModule_28; }
    if ((token === import3.MdSelectModule)) { return this._MdSelectModule_29; }
    if ((token === import3.MdSidenavModule)) { return this._MdSidenavModule_30; }
    if ((token === import3.RtlModule)) { return this._RtlModule_31; }
    if ((token === import3.MdSliderModule)) { return this._MdSliderModule_32; }
    if ((token === import3.MdSlideToggleModule)) { return this._MdSlideToggleModule_33; }
    if ((token === import3.MdSnackBarModule)) { return this._MdSnackBarModule_34; }
    if ((token === import3.ObserveContentModule)) { return this._ObserveContentModule_35; }
    if ((token === import3.MdTabsModule)) { return this._MdTabsModule_36; }
    if ((token === import3.MdToolbarModule)) { return this._MdToolbarModule_37; }
    if ((token === import3.MdTooltipModule)) { return this._MdTooltipModule_38; }
    if ((token === import3.MaterialModule)) { return this._MaterialModule_39; }
    if ((token === import6.MediaQueriesModule)) { return this._MediaQueriesModule_40; }
    if ((token === import7.FlexLayoutModule)) { return this._FlexLayoutModule_41; }
    if ((token === import8.CardModule)) { return this._CardModule_42; }
    if ((token === import9.RouterModule)) { return this._RouterModule_43; }
    if ((token === import1.UserProfileModule)) { return this._UserProfileModule_44; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_45; }
    if ((token === import3.ScrollDispatcher)) { return this._ScrollDispatcher_46; }
    if ((token === import3.ɵh)) { return this._ɵh_47; }
    if ((token === import3.OverlayContainer)) { return this._OverlayContainer_48; }
    if ((token === import3.ɵk)) { return this._ɵk_49; }
    if ((token === import3.Overlay)) { return this._Overlay_50; }
    if ((token === import3.FocusOriginMonitor)) { return this._FocusOriginMonitor_51; }
    if ((token === import4.ɵi)) { return this._ɵi_52; }
    if ((token === import3.UniqueSelectionDispatcher)) { return this._UniqueSelectionDispatcher_53; }
    if ((token === import3.Platform)) { return this._Platform_54; }
    if ((token === import3.InteractivityChecker)) { return this._InteractivityChecker_55; }
    if ((token === import3.FocusTrapFactory)) { return this._FocusTrapFactory_56; }
    if ((token === import3.LiveAnnouncer)) { return this._LiveAnnouncer_57; }
    if ((token === import3.MdDialog)) { return this._MdDialog_58; }
    if ((token === import5.BrowserXhr)) { return this._BrowserXhr_59; }
    if ((token === import5.ResponseOptions)) { return this._ResponseOptions_60; }
    if ((token === import5.XSRFStrategy)) { return this._XSRFStrategy_61; }
    if ((token === import5.XHRBackend)) { return this._XHRBackend_62; }
    if ((token === import5.RequestOptions)) { return this._RequestOptions_63; }
    if ((token === import5.Http)) { return this._Http_64; }
    if ((token === import3.MdIconRegistry)) { return this._MdIconRegistry_65; }
    if ((token === import17.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_66; }
    if ((token === import3.MdSnackBar)) { return this._MdSnackBar_67; }
    if ((token === import27.BREAKPOINTS)) { return this._BREAKPOINTS_68; }
    if ((token === import10.BreakPointRegistry)) { return this._BreakPointRegistry_69; }
    if ((token === import11.MatchMedia)) { return this._MatchMedia_70; }
    if ((token === import20.MediaMonitor)) { return this._MediaMonitor_71; }
    if ((token === import22.ObservableMedia)) { return this._ObservableMedia_72; }
    if ((token === import12.ApiService)) { return this._ApiService_73; }
    if ((token === import9.ROUTES)) { return this._ROUTES_74; }
    if ((token === import13.AvatarService)) { return this._AvatarService_75; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const UserProfileModuleNgFactory:import0.NgModuleFactory<import1.UserProfileModule> = new import0.NgModuleFactory<any>(UserProfileModuleInjector,import1.UserProfileModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL3N0dWRlbnQvdXNlci1wcm9maWxlL3VzZXItcHJvZmlsZS5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL3N0dWRlbnQvdXNlci1wcm9maWxlL3VzZXItcHJvZmlsZS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
