/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.container[_ngcontent-%COMP%] {\r\n    height: 50px;\r\n    margin: auto;\r\n}\r\n\r\n.words[_ngcontent-%COMP%] {\r\n    width: 200px;\r\n    margin-bottom: 3px;\r\n    text-align:center;\r\n    border: solid black;\r\n}\r\n\r\n.drop[_ngcontent-%COMP%] {\r\n    display: inline-block;\r\n    width: 200px;\r\n    border: dotted black;\r\n}\r\n\r\n.defs[_ngcontent-%COMP%] {\r\n    vertical-align: top;\r\n    display: inline-block;\r\n    width: 300px;      \r\n    margin-right: 3px; \r\n    border: solid black;\r\n}\r\n\r\n.wrapper[_ngcontent-%COMP%] {\r\n    text-align:center;\r\n    min-width: 550px;\r\n    margin-bottom: 3px;\r\n}\r\n\r\nh1[_ngcontent-%COMP%] {\r\n    font-family: Georgia, "Times New Roman";\r\n    text-align: center;\r\n    font-size: 28px;\r\n    margin-bottom: 20px;\r\n}\r\n\r\n.score[_ngcontent-%COMP%] {\r\n    float: right;\r\n    margin-bottom: 10px;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL3N0dWRlbnQvZ2FtZXMvdm9jYWItbWF0Y2gvdm9jYWItbWF0Y2guY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9NYWhhZWxhL0Rlc2t0b3Avc2Nob2xhcnF1ZXN0LXJlZmFjdG9yL2Fzc2V0cy9hcHAvc3R1ZGVudC9nYW1lcy92b2NhYi1tYXRjaC92b2NhYi1tYXRjaC5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
