/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['img[_ngcontent-%COMP%] {\r\n    display: block;\r\n    width: 90px;\r\n    height: 90px;\r\n    margin: auto;  \r\n    background-color: white;\r\n}\r\n\r\nmd-grid-tile[_ngcontent-%COMP%] {\r\n    border: solid grey 2px;\r\n    cursor: pointer;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL3NoYXJlZC9jYXJkL2J1dHRvbi1ncmlkLWNhcmQvYnV0dG9uLWdyaWQtY2FyZC5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL01haGFlbGEvRGVza3RvcC9zY2hvbGFycXVlc3QtcmVmYWN0b3IvYXNzZXRzL2FwcC9zaGFyZWQvY2FyZC9idXR0b24tZ3JpZC1jYXJkL2J1dHRvbi1ncmlkLWNhcmQuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
