/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['#wrapper[_ngcontent-%COMP%]{\r\n    height: 500px;\r\n    width: 510px;\r\n    margin: auto;\r\n}\r\n#bwrapper[_ngcontent-%COMP%]{\r\n    text-align: center;\r\n}\r\n\r\ninput[_ngcontent-%COMP%]{\r\n    width: 505px;\r\n}\r\n\r\n.error[_ngcontent-%COMP%]{\r\n    color: orangered;\r\n    text-align: center;\r\n}\r\n\r\nh1[_ngcontent-%COMP%]{\r\n   text-align: center;\r\n}\r\n\r\n.container[_ngcontent-%COMP%]{\r\n    background-color:cornsilk;\r\n    height: 500px;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL2F1dGgvbG9naW4vbG9naW4uY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9NYWhhZWxhL0Rlc2t0b3Avc2Nob2xhcnF1ZXN0LXJlZmFjdG9yL2Fzc2V0cy9hcHAvYXV0aC9sb2dpbi9sb2dpbi5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
