/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './home.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from './home.component';
const styles_HomeComponent:any[] = [import0.styles];
export const RenderType_HomeComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_HomeComponent,
  data: {}
}
);
export function View_HomeComponent_0(l:any):import1.ɵViewDefinition {
      return import1.ɵvid(0,[(l()(),import1.ɵeld(0,(null as any),(null as any),0,'img',[[
        'src',
        '../assets/clip-art/SQ.png'
      ]
  ],(null as any),(null as any),(null as any),(null as any),(null as any)))],(null as any),(null as any));
}
function View_HomeComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'sq-home',([] as any[]),(null as any),(null as any),(null as any),View_HomeComponent_0,RenderType_HomeComponent)),
    import1.ɵdid(24576,(null as any),0,import2.HomeComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const HomeComponentNgFactory:import1.ComponentFactory<import2.HomeComponent> = import1.ɵccf('sq-home',import2.HomeComponent,View_HomeComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL2hvbWUvaG9tZS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL2hvbWUvaG9tZS5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9NYWhhZWxhL0Rlc2t0b3Avc2Nob2xhcnF1ZXN0LXJlZmFjdG9yL2Fzc2V0cy9hcHAvaG9tZS9ob21lLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL2hvbWUvaG9tZS5jb21wb25lbnQudHMuSG9tZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxpbWcgc3JjPVwiLi4vYXNzZXRzL2NsaXAtYXJ0L1NRLnBuZ1wiPiIsIjxzcS1ob21lPjwvc3EtaG9tZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OzZCQ0FBO1FBQUE7UUFBQTtNQUFBO0VBQUE7Ozs7SUNBQTtnQkFBQTs7OzsifQ==
