/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './auth.module';
import * as import2 from '@angular/material';
import * as import3 from '@angular/common';
import * as import4 from '@angular/forms';
import * as import5 from '@angular/http';
import * as import6 from '@angular/flex-layout/media-query/_module';
import * as import7 from '@angular/flex-layout/flexbox/_module';
import * as import8 from '@angular/router';
import * as import9 from '@angular/flex-layout/media-query/breakpoints/break-point-registry';
import * as import10 from '@angular/flex-layout/media-query/match-media';
import * as import11 from '../../../node_modules/@angular/material/typings/index.ngfactory';
import * as import12 from './signup/signup.component.ngfactory';
import * as import13 from './login/login.component.ngfactory';
import * as import14 from './welcome-email-sent/welcome-email-sent.component.ngfactory';
import * as import15 from './email-verified/email-verified.component.ngfactory';
import * as import16 from '@angular/platform-browser';
import * as import17 from '@angular/flex-layout/media-query/breakpoints/break-points-provider';
import * as import18 from '@angular/flex-layout/media-query/media-monitor-provider';
import * as import19 from '@angular/flex-layout/media-query/media-monitor';
import * as import20 from '@angular/flex-layout/media-query/observable-media-provider';
import * as import21 from '@angular/flex-layout/media-query/observable-media';
import * as import22 from './signup/signup.component';
import * as import23 from './login/login.component';
import * as import24 from './welcome-email-sent/welcome-email-sent.component';
import * as import25 from './email-verified/email-verified.component';
import * as import26 from '@angular/flex-layout/media-query/breakpoints/break-points-token';
class AuthModuleInjector extends import0.ɵNgModuleInjector<import1.AuthModule> {
  _CompatibilityModule_0:import2.CompatibilityModule;
  _MdRippleModule_1:import2.MdRippleModule;
  _CommonModule_2:import3.CommonModule;
  _MdSelectionModule_3:import2.MdSelectionModule;
  _MdOptionModule_4:import2.MdOptionModule;
  _PortalModule_5:import2.PortalModule;
  _OverlayModule_6:import2.OverlayModule;
  _MdAutocompleteModule_7:import2.MdAutocompleteModule;
  _StyleModule_8:import2.StyleModule;
  _MdButtonModule_9:import2.MdButtonModule;
  _ɵba_10:import4.ɵba;
  _FormsModule_11:import4.FormsModule;
  _MdButtonToggleModule_12:import2.MdButtonToggleModule;
  _MdCardModule_13:import2.MdCardModule;
  _MdChipsModule_14:import2.MdChipsModule;
  _MdCheckboxModule_15:import2.MdCheckboxModule;
  _PlatformModule_16:import2.PlatformModule;
  _A11yModule_17:import2.A11yModule;
  _MdDialogModule_18:import2.MdDialogModule;
  _MdLineModule_19:import2.MdLineModule;
  _MdGridListModule_20:import2.MdGridListModule;
  _HttpModule_21:import5.HttpModule;
  _MdIconModule_22:import2.MdIconModule;
  _MdInputModule_23:import2.MdInputModule;
  _MdListModule_24:import2.MdListModule;
  _MdMenuModule_25:import2.MdMenuModule;
  _MdProgressBarModule_26:import2.MdProgressBarModule;
  _MdProgressSpinnerModule_27:import2.MdProgressSpinnerModule;
  _MdRadioModule_28:import2.MdRadioModule;
  _MdSelectModule_29:import2.MdSelectModule;
  _MdSidenavModule_30:import2.MdSidenavModule;
  _RtlModule_31:import2.RtlModule;
  _MdSliderModule_32:import2.MdSliderModule;
  _MdSlideToggleModule_33:import2.MdSlideToggleModule;
  _MdSnackBarModule_34:import2.MdSnackBarModule;
  _ObserveContentModule_35:import2.ObserveContentModule;
  _MdTabsModule_36:import2.MdTabsModule;
  _MdToolbarModule_37:import2.MdToolbarModule;
  _MdTooltipModule_38:import2.MdTooltipModule;
  _MaterialModule_39:import2.MaterialModule;
  _MediaQueriesModule_40:import6.MediaQueriesModule;
  _FlexLayoutModule_41:import7.FlexLayoutModule;
  _RouterModule_42:import8.RouterModule;
  _ReactiveFormsModule_43:import4.ReactiveFormsModule;
  _AuthModule_44:import1.AuthModule;
  __ScrollDispatcher_45:any;
  __ɵh_46:any;
  __NgLocalization_47:import3.NgLocaleLocalization;
  __OverlayContainer_48:any;
  __ɵk_49:import2.ɵk;
  __Overlay_50:import2.Overlay;
  __FocusOriginMonitor_51:any;
  __ɵi_52:import4.ɵi;
  __UniqueSelectionDispatcher_53:any;
  __Platform_54:import2.Platform;
  __InteractivityChecker_55:import2.InteractivityChecker;
  __FocusTrapFactory_56:import2.FocusTrapFactory;
  __LiveAnnouncer_57:any;
  __MdDialog_58:import2.MdDialog;
  __BrowserXhr_59:import5.BrowserXhr;
  __ResponseOptions_60:import5.BaseResponseOptions;
  __XSRFStrategy_61:any;
  __XHRBackend_62:import5.XHRBackend;
  __RequestOptions_63:import5.BaseRequestOptions;
  __Http_64:any;
  __MdIconRegistry_65:any;
  __HAMMER_GESTURE_CONFIG_66:import2.GestureConfig;
  __MdSnackBar_67:import2.MdSnackBar;
  __BREAKPOINTS_68:any;
  __BreakPointRegistry_69:import9.BreakPointRegistry;
  __MatchMedia_70:import10.MatchMedia;
  __MediaMonitor_71:any;
  __ObservableMedia_72:any;
  __FormBuilder_73:import4.FormBuilder;
  _ROUTES_74:any[];
  constructor(parent:import0.Injector) {
    super(parent,[
      import11.MdDialogContainerNgFactory,
      import11.MdSnackBarContainerNgFactory,
      import11.SimpleSnackBarNgFactory,
      import11.TooltipComponentNgFactory,
      import12.SignupComponentNgFactory,
      import13.LoginComponentNgFactory,
      import14.WelcomeEmailSentComponentNgFactory,
      import15.EmailVerifiedComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _ScrollDispatcher_45():any {
    if ((this.__ScrollDispatcher_45 == null)) { (this.__ScrollDispatcher_45 = import2.ɵc(this.parent.get(import2.ScrollDispatcher,(null as any)),this.parent.get(import0.NgZone))); }
    return this.__ScrollDispatcher_45;
  }
  get _ɵh_46():any {
    if ((this.__ɵh_46 == null)) { (this.__ɵh_46 = import2.ɵi(this.parent.get(import2.ɵh,(null as any)),this._ScrollDispatcher_45)); }
    return this.__ɵh_46;
  }
  get _NgLocalization_47():import3.NgLocaleLocalization {
    if ((this.__NgLocalization_47 == null)) { (this.__NgLocalization_47 = new import3.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_47;
  }
  get _OverlayContainer_48():any {
    if ((this.__OverlayContainer_48 == null)) { (this.__OverlayContainer_48 = import2.ɵa(this.parent.get(import2.OverlayContainer,(null as any)))); }
    return this.__OverlayContainer_48;
  }
  get _ɵk_49():import2.ɵk {
    if ((this.__ɵk_49 == null)) { (this.__ɵk_49 = new import2.ɵk(this._ɵh_46)); }
    return this.__ɵk_49;
  }
  get _Overlay_50():import2.Overlay {
    if ((this.__Overlay_50 == null)) { (this.__Overlay_50 = new import2.Overlay(this._OverlayContainer_48,this.componentFactoryResolver,this._ɵk_49,this.parent.get(import0.ApplicationRef),this,this.parent.get(import0.NgZone))); }
    return this.__Overlay_50;
  }
  get _FocusOriginMonitor_51():any {
    if ((this.__FocusOriginMonitor_51 == null)) { (this.__FocusOriginMonitor_51 = import2.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY(this.parent.get(import2.FocusOriginMonitor,(null as any)),this.parent.get(import0.NgZone))); }
    return this.__FocusOriginMonitor_51;
  }
  get _ɵi_52():import4.ɵi {
    if ((this.__ɵi_52 == null)) { (this.__ɵi_52 = new import4.ɵi()); }
    return this.__ɵi_52;
  }
  get _UniqueSelectionDispatcher_53():any {
    if ((this.__UniqueSelectionDispatcher_53 == null)) { (this.__UniqueSelectionDispatcher_53 = import2.ɵg(this.parent.get(import2.UniqueSelectionDispatcher,(null as any)))); }
    return this.__UniqueSelectionDispatcher_53;
  }
  get _Platform_54():import2.Platform {
    if ((this.__Platform_54 == null)) { (this.__Platform_54 = new import2.Platform()); }
    return this.__Platform_54;
  }
  get _InteractivityChecker_55():import2.InteractivityChecker {
    if ((this.__InteractivityChecker_55 == null)) { (this.__InteractivityChecker_55 = new import2.InteractivityChecker(this._Platform_54)); }
    return this.__InteractivityChecker_55;
  }
  get _FocusTrapFactory_56():import2.FocusTrapFactory {
    if ((this.__FocusTrapFactory_56 == null)) { (this.__FocusTrapFactory_56 = new import2.FocusTrapFactory(this._InteractivityChecker_55,this.parent.get(import0.NgZone))); }
    return this.__FocusTrapFactory_56;
  }
  get _LiveAnnouncer_57():any {
    if ((this.__LiveAnnouncer_57 == null)) { (this.__LiveAnnouncer_57 = import2.ɵf(this.parent.get(import2.LiveAnnouncer,(null as any)),this.parent.get(import2.LIVE_ANNOUNCER_ELEMENT_TOKEN,(null as any)))); }
    return this.__LiveAnnouncer_57;
  }
  get _MdDialog_58():import2.MdDialog {
    if ((this.__MdDialog_58 == null)) { (this.__MdDialog_58 = new import2.MdDialog(this._Overlay_50,this,this.parent.get(import2.MdDialog,(null as any)))); }
    return this.__MdDialog_58;
  }
  get _BrowserXhr_59():import5.BrowserXhr {
    if ((this.__BrowserXhr_59 == null)) { (this.__BrowserXhr_59 = new import5.BrowserXhr()); }
    return this.__BrowserXhr_59;
  }
  get _ResponseOptions_60():import5.BaseResponseOptions {
    if ((this.__ResponseOptions_60 == null)) { (this.__ResponseOptions_60 = new import5.BaseResponseOptions()); }
    return this.__ResponseOptions_60;
  }
  get _XSRFStrategy_61():any {
    if ((this.__XSRFStrategy_61 == null)) { (this.__XSRFStrategy_61 = import5.ɵb()); }
    return this.__XSRFStrategy_61;
  }
  get _XHRBackend_62():import5.XHRBackend {
    if ((this.__XHRBackend_62 == null)) { (this.__XHRBackend_62 = new import5.XHRBackend(this._BrowserXhr_59,this._ResponseOptions_60,this._XSRFStrategy_61)); }
    return this.__XHRBackend_62;
  }
  get _RequestOptions_63():import5.BaseRequestOptions {
    if ((this.__RequestOptions_63 == null)) { (this.__RequestOptions_63 = new import5.BaseRequestOptions()); }
    return this.__RequestOptions_63;
  }
  get _Http_64():any {
    if ((this.__Http_64 == null)) { (this.__Http_64 = import5.ɵc(this._XHRBackend_62,this._RequestOptions_63)); }
    return this.__Http_64;
  }
  get _MdIconRegistry_65():any {
    if ((this.__MdIconRegistry_65 == null)) { (this.__MdIconRegistry_65 = import2.ICON_REGISTRY_PROVIDER_FACTORY(this.parent.get(import2.MdIconRegistry,(null as any)),this._Http_64,this.parent.get(import16.DomSanitizer))); }
    return this.__MdIconRegistry_65;
  }
  get _HAMMER_GESTURE_CONFIG_66():import2.GestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_66 == null)) { (this.__HAMMER_GESTURE_CONFIG_66 = new import2.GestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_66;
  }
  get _MdSnackBar_67():import2.MdSnackBar {
    if ((this.__MdSnackBar_67 == null)) { (this.__MdSnackBar_67 = new import2.MdSnackBar(this._Overlay_50,this._LiveAnnouncer_57,this.parent.get(import2.MdSnackBar,(null as any)))); }
    return this.__MdSnackBar_67;
  }
  get _BREAKPOINTS_68():any {
    if ((this.__BREAKPOINTS_68 == null)) { (this.__BREAKPOINTS_68 = import17.DEFAULT_BREAKPOINTS_PROVIDER_FACTORY()); }
    return this.__BREAKPOINTS_68;
  }
  get _BreakPointRegistry_69():import9.BreakPointRegistry {
    if ((this.__BreakPointRegistry_69 == null)) { (this.__BreakPointRegistry_69 = new import9.BreakPointRegistry(this._BREAKPOINTS_68)); }
    return this.__BreakPointRegistry_69;
  }
  get _MatchMedia_70():import10.MatchMedia {
    if ((this.__MatchMedia_70 == null)) { (this.__MatchMedia_70 = new import10.MatchMedia(this.parent.get(import0.NgZone))); }
    return this.__MatchMedia_70;
  }
  get _MediaMonitor_71():any {
    if ((this.__MediaMonitor_71 == null)) { (this.__MediaMonitor_71 = import18.MEDIA_MONITOR_PROVIDER_FACTORY(this.parent.get(import19.MediaMonitor,(null as any)),this._BreakPointRegistry_69,this._MatchMedia_70)); }
    return this.__MediaMonitor_71;
  }
  get _ObservableMedia_72():any {
    if ((this.__ObservableMedia_72 == null)) { (this.__ObservableMedia_72 = import20.OBSERVABLE_MEDIA_PROVIDER_FACTORY(this.parent.get(import21.ObservableMedia,(null as any)),this._MatchMedia_70,this._BreakPointRegistry_69)); }
    return this.__ObservableMedia_72;
  }
  get _FormBuilder_73():import4.FormBuilder {
    if ((this.__FormBuilder_73 == null)) { (this.__FormBuilder_73 = new import4.FormBuilder()); }
    return this.__FormBuilder_73;
  }
  createInternal():import1.AuthModule {
    this._CompatibilityModule_0 = new import2.CompatibilityModule(this.parent.get(import16.DOCUMENT,(null as any)));
    this._MdRippleModule_1 = new import2.MdRippleModule();
    this._CommonModule_2 = new import3.CommonModule();
    this._MdSelectionModule_3 = new import2.MdSelectionModule();
    this._MdOptionModule_4 = new import2.MdOptionModule();
    this._PortalModule_5 = new import2.PortalModule();
    this._OverlayModule_6 = new import2.OverlayModule();
    this._MdAutocompleteModule_7 = new import2.MdAutocompleteModule();
    this._StyleModule_8 = new import2.StyleModule();
    this._MdButtonModule_9 = new import2.MdButtonModule();
    this._ɵba_10 = new import4.ɵba();
    this._FormsModule_11 = new import4.FormsModule();
    this._MdButtonToggleModule_12 = new import2.MdButtonToggleModule();
    this._MdCardModule_13 = new import2.MdCardModule();
    this._MdChipsModule_14 = new import2.MdChipsModule();
    this._MdCheckboxModule_15 = new import2.MdCheckboxModule();
    this._PlatformModule_16 = new import2.PlatformModule();
    this._A11yModule_17 = new import2.A11yModule();
    this._MdDialogModule_18 = new import2.MdDialogModule();
    this._MdLineModule_19 = new import2.MdLineModule();
    this._MdGridListModule_20 = new import2.MdGridListModule();
    this._HttpModule_21 = new import5.HttpModule();
    this._MdIconModule_22 = new import2.MdIconModule();
    this._MdInputModule_23 = new import2.MdInputModule();
    this._MdListModule_24 = new import2.MdListModule();
    this._MdMenuModule_25 = new import2.MdMenuModule();
    this._MdProgressBarModule_26 = new import2.MdProgressBarModule();
    this._MdProgressSpinnerModule_27 = new import2.MdProgressSpinnerModule();
    this._MdRadioModule_28 = new import2.MdRadioModule();
    this._MdSelectModule_29 = new import2.MdSelectModule();
    this._MdSidenavModule_30 = new import2.MdSidenavModule();
    this._RtlModule_31 = new import2.RtlModule();
    this._MdSliderModule_32 = new import2.MdSliderModule();
    this._MdSlideToggleModule_33 = new import2.MdSlideToggleModule();
    this._MdSnackBarModule_34 = new import2.MdSnackBarModule();
    this._ObserveContentModule_35 = new import2.ObserveContentModule();
    this._MdTabsModule_36 = new import2.MdTabsModule();
    this._MdToolbarModule_37 = new import2.MdToolbarModule();
    this._MdTooltipModule_38 = new import2.MdTooltipModule();
    this._MaterialModule_39 = new import2.MaterialModule();
    this._MediaQueriesModule_40 = new import6.MediaQueriesModule();
    this._FlexLayoutModule_41 = new import7.FlexLayoutModule();
    this._RouterModule_42 = new import8.RouterModule(this.parent.get(import8.ɵa,(null as any)),this.parent.get(import8.Router,(null as any)));
    this._ReactiveFormsModule_43 = new import4.ReactiveFormsModule();
    this._AuthModule_44 = new import1.AuthModule();
      this._ROUTES_74 = [[
        {
          path: '',
          component: import22.SignupComponent
        }
        ,
        {
          path: 'signup',
          component: import22.SignupComponent
        }
        ,
        {
          path: 'login',
          component: import23.LoginComponent
        }
        ,
        {
          path: 'welcome',
          component: import24.WelcomeEmailSentComponent
        }
        ,
        {
          path: 'verified/:id',
          component: import25.EmailVerifiedComponent
        }

      ]
    ];
    return this._AuthModule_44;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CompatibilityModule)) { return this._CompatibilityModule_0; }
    if ((token === import2.MdRippleModule)) { return this._MdRippleModule_1; }
    if ((token === import3.CommonModule)) { return this._CommonModule_2; }
    if ((token === import2.MdSelectionModule)) { return this._MdSelectionModule_3; }
    if ((token === import2.MdOptionModule)) { return this._MdOptionModule_4; }
    if ((token === import2.PortalModule)) { return this._PortalModule_5; }
    if ((token === import2.OverlayModule)) { return this._OverlayModule_6; }
    if ((token === import2.MdAutocompleteModule)) { return this._MdAutocompleteModule_7; }
    if ((token === import2.StyleModule)) { return this._StyleModule_8; }
    if ((token === import2.MdButtonModule)) { return this._MdButtonModule_9; }
    if ((token === import4.ɵba)) { return this._ɵba_10; }
    if ((token === import4.FormsModule)) { return this._FormsModule_11; }
    if ((token === import2.MdButtonToggleModule)) { return this._MdButtonToggleModule_12; }
    if ((token === import2.MdCardModule)) { return this._MdCardModule_13; }
    if ((token === import2.MdChipsModule)) { return this._MdChipsModule_14; }
    if ((token === import2.MdCheckboxModule)) { return this._MdCheckboxModule_15; }
    if ((token === import2.PlatformModule)) { return this._PlatformModule_16; }
    if ((token === import2.A11yModule)) { return this._A11yModule_17; }
    if ((token === import2.MdDialogModule)) { return this._MdDialogModule_18; }
    if ((token === import2.MdLineModule)) { return this._MdLineModule_19; }
    if ((token === import2.MdGridListModule)) { return this._MdGridListModule_20; }
    if ((token === import5.HttpModule)) { return this._HttpModule_21; }
    if ((token === import2.MdIconModule)) { return this._MdIconModule_22; }
    if ((token === import2.MdInputModule)) { return this._MdInputModule_23; }
    if ((token === import2.MdListModule)) { return this._MdListModule_24; }
    if ((token === import2.MdMenuModule)) { return this._MdMenuModule_25; }
    if ((token === import2.MdProgressBarModule)) { return this._MdProgressBarModule_26; }
    if ((token === import2.MdProgressSpinnerModule)) { return this._MdProgressSpinnerModule_27; }
    if ((token === import2.MdRadioModule)) { return this._MdRadioModule_28; }
    if ((token === import2.MdSelectModule)) { return this._MdSelectModule_29; }
    if ((token === import2.MdSidenavModule)) { return this._MdSidenavModule_30; }
    if ((token === import2.RtlModule)) { return this._RtlModule_31; }
    if ((token === import2.MdSliderModule)) { return this._MdSliderModule_32; }
    if ((token === import2.MdSlideToggleModule)) { return this._MdSlideToggleModule_33; }
    if ((token === import2.MdSnackBarModule)) { return this._MdSnackBarModule_34; }
    if ((token === import2.ObserveContentModule)) { return this._ObserveContentModule_35; }
    if ((token === import2.MdTabsModule)) { return this._MdTabsModule_36; }
    if ((token === import2.MdToolbarModule)) { return this._MdToolbarModule_37; }
    if ((token === import2.MdTooltipModule)) { return this._MdTooltipModule_38; }
    if ((token === import2.MaterialModule)) { return this._MaterialModule_39; }
    if ((token === import6.MediaQueriesModule)) { return this._MediaQueriesModule_40; }
    if ((token === import7.FlexLayoutModule)) { return this._FlexLayoutModule_41; }
    if ((token === import8.RouterModule)) { return this._RouterModule_42; }
    if ((token === import4.ReactiveFormsModule)) { return this._ReactiveFormsModule_43; }
    if ((token === import1.AuthModule)) { return this._AuthModule_44; }
    if ((token === import2.ScrollDispatcher)) { return this._ScrollDispatcher_45; }
    if ((token === import2.ɵh)) { return this._ɵh_46; }
    if ((token === import3.NgLocalization)) { return this._NgLocalization_47; }
    if ((token === import2.OverlayContainer)) { return this._OverlayContainer_48; }
    if ((token === import2.ɵk)) { return this._ɵk_49; }
    if ((token === import2.Overlay)) { return this._Overlay_50; }
    if ((token === import2.FocusOriginMonitor)) { return this._FocusOriginMonitor_51; }
    if ((token === import4.ɵi)) { return this._ɵi_52; }
    if ((token === import2.UniqueSelectionDispatcher)) { return this._UniqueSelectionDispatcher_53; }
    if ((token === import2.Platform)) { return this._Platform_54; }
    if ((token === import2.InteractivityChecker)) { return this._InteractivityChecker_55; }
    if ((token === import2.FocusTrapFactory)) { return this._FocusTrapFactory_56; }
    if ((token === import2.LiveAnnouncer)) { return this._LiveAnnouncer_57; }
    if ((token === import2.MdDialog)) { return this._MdDialog_58; }
    if ((token === import5.BrowserXhr)) { return this._BrowserXhr_59; }
    if ((token === import5.ResponseOptions)) { return this._ResponseOptions_60; }
    if ((token === import5.XSRFStrategy)) { return this._XSRFStrategy_61; }
    if ((token === import5.XHRBackend)) { return this._XHRBackend_62; }
    if ((token === import5.RequestOptions)) { return this._RequestOptions_63; }
    if ((token === import5.Http)) { return this._Http_64; }
    if ((token === import2.MdIconRegistry)) { return this._MdIconRegistry_65; }
    if ((token === import16.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_66; }
    if ((token === import2.MdSnackBar)) { return this._MdSnackBar_67; }
    if ((token === import26.BREAKPOINTS)) { return this._BREAKPOINTS_68; }
    if ((token === import9.BreakPointRegistry)) { return this._BreakPointRegistry_69; }
    if ((token === import10.MatchMedia)) { return this._MatchMedia_70; }
    if ((token === import19.MediaMonitor)) { return this._MediaMonitor_71; }
    if ((token === import21.ObservableMedia)) { return this._ObservableMedia_72; }
    if ((token === import4.FormBuilder)) { return this._FormBuilder_73; }
    if ((token === import8.ROUTES)) { return this._ROUTES_74; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AuthModuleNgFactory:import0.NgModuleFactory<import1.AuthModule> = new import0.NgModuleFactory<any>(AuthModuleInjector,import1.AuthModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL2F1dGgvYXV0aC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL2F1dGgvYXV0aC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
