/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.block[_ngcontent-%COMP%] {\r\n    display: inline-block;\r\n}\r\n\r\n.icon[_ngcontent-%COMP%] {\r\n    width: 40px;\r\n    height: 40px\r\n}\r\n\r\nbutton[_ngcontent-%COMP%] {\r\n    display: block;\r\n    width: 55px;\r\n    height: 55px;\r\n    margin: auto;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL3N0dWRlbnQvdXNlci1wcm9maWxlL3VzZXItcHJvZmlsZS1wYWdlL3VzZXItcHJvZmlsZS1wYWdlLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL3N0dWRlbnQvdXNlci1wcm9maWxlL3VzZXItcHJvZmlsZS1wYWdlL3VzZXItcHJvZmlsZS1wYWdlLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
