/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.dropBox[_ngcontent-%COMP%] {\r\n    width: 100px;\r\n    height: 100px;\r\n    background-color: red;\r\n    border: solid black 1px;\r\n}\r\n\r\n.partsBox[_ngcontent-%COMP%]{\r\n    background-color: blue;\r\n    width: 100px;\r\n    height: 100px;\r\n    border: solid black 1px;\r\n}\r\n .endBox[_ngcontent-%COMP%]{\r\n    background-color: green;\r\n    min-width: 100px;\r\n    max-width: 250px;\r\n    height: 100px;\r\n    border: solid black 1px;\r\n    \r\n }\r\n\r\n .startBox[_ngcontent-%COMP%] {\r\n    background-color: purple;\r\n    width: 100px;\r\n    height: 100px;\r\n    border: solid black 1px;\r\n }\r\n\r\n .dragImg[_ngcontent-%COMP%] {\r\n     height: 100px;\r\n }\r\n \r\n .dropImg[_ngcontent-%COMP%] {\r\n     visibility: hidden;\r\n     height: 98px;\r\n }\r\n\r\n .title[_ngcontent-%COMP%] {\r\n     text-align: center;\r\n }\r\n\r\n .big-table[_ngcontent-%COMP%] {\r\n     margin: auto;\r\n }'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL3N0dWRlbnQvZ2FtZXMvd29yZC1waXBlcy93b3JkLXBpcGVzLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL3N0dWRlbnQvZ2FtZXMvd29yZC1waXBlcy93b3JkLXBpcGVzLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
