/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.coin[_ngcontent-%COMP%] {\r\n    width: 20px;\r\n    height: 20px;\r\n    display: inline-block;\r\n}\r\n\r\n#coinWrapper[_ngcontent-%COMP%] {\r\n    width: 150px;\r\n}\r\n\r\na[_ngcontent-%COMP%] {\r\n    padding-right: 4%;\r\n    text-decoration: none;\r\n    text-align: center;\r\n}\r\n\r\nbutton[_ngcontent-%COMP%]:focus {outline:0;}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvTWFoYWVsYS9EZXNrdG9wL3NjaG9sYXJxdWVzdC1yZWZhY3Rvci9hc3NldHMvYXBwL25hdmJhci9uYXZiYXIuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9NYWhhZWxhL0Rlc2t0b3Avc2Nob2xhcnF1ZXN0LXJlZmFjdG9yL2Fzc2V0cy9hcHAvbmF2YmFyL25hdmJhci5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
